spring.application.name=Gestor Facil

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

jwt.secret=${JWT_SECRET:chave-padrao-desenvolvimento-64-caracteres-minimo-para-hs256-seguranca}
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

server.port=8080

email.mock=${EMAIL_MOCK:true}

integracao.banco.url-base=${INTEGRACAO_BANCO_URL:http://localhost:8090/v1}
integracao.cambio.url-base=${INTEGRACAO_CAMBIO_URL:https://brasilapi.com.br/api/cambio/v1}
