spring.application.name=Gestor Facil

spring.datasource.url=jdbc:postgresql://db:5432/gestorfacil_db
spring.datasource.username=admindb
spring.datasource.password=admindb123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=jonatas
spring.security.user.password={noop}jonatas88199115

spring.data.redis.host=redis
spring.data.redis.port=6379

jwt.secret=${JWT_SECRET:chave-docker-desenvolvimento-64-caracteres-minimo-algoritmo-hs256}
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

email.mock=true

integracao.banco.url-base=http://wiremock:8080/v1

server.port=8080
